# Generated by Django 5.0.6 on 2024-06-01 05:28

import AssetManagerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0035_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=AssetManagerApp.models.user_directory_path),
        ),
    ]
