# Generated by Django 5.0.6 on 2024-06-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0036_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='space',
            name='pinned',
            field=models.IntegerField(default=False),
        ),
    ]
